### ISSUE TITLE
 Can I modify the code to obtain the json files?

### ISSUE THREAD

**Issue by Sevenrs** [Icseon/tbot-dungeon-tools#1]
Hello icon, a question, can you give me a clue on what to do to be able to obtain the dungeon and map planet json files? thank you

**Comment by Icseon** [comment]
I do not offer support. You could make the scripts perform in a reverse fashion — so instead of writing, you read instead. 

I don’t work on this game anymore, so you’ll have to figure that out on your own. This repository does serve as a starting point.

**Comment by Sevenrs** [comment]
thanks for the information
